Repository DEFRA/defra-ruby-validators, pull requests merged in 2019-08, with the labels that each got.

#33 Enable the gem to use custom validation error messages
  lib/defra_ruby/validators/base_validator.rb
  spec/cassettes/company_no_inactive.yml
  spec/cassettes/company_no_not_found.yml
  spec/cassettes/company_no_valid.yml
  spec/spec_helper.rb
  spec/support/dotenv.rb
  spec/support/shared_examples/validators/invalid_record.rb
Labels: enhancement

#34 TrueFalseValidator uses correct attribute
  lib/defra_ruby/validators/true_false_validator.rb
Labels: bug

#35 Enable gem to receive multiple custom error messages
  lib/defra_ruby/validators/base_validator.rb
  spec/defra_ruby/validators/companies_house_number_validator_spec.rb
  spec/defra_ruby/validators/email_validator_spec.rb
  spec/defra_ruby/validators/grid_reference_validator_spec.rb
  spec/defra_ruby/validators/phone_number_validator_spec.rb
  spec/defra_ruby/validators/token_validator_spec.rb
  spec/support/shared_examples/validators/characters_validator.rb
  spec/support/shared_examples/validators/invalid_record.rb
  spec/support/shared_examples/validators/length_validator.rb
  spec/support/shared_examples/validators/presence_validator.rb
  spec/support/shared_examples/validators/selection_validator.rb
Labels: enhancement

#36 Standardise invalid format errors
  config/locales/defra_ruby/validators/companies_house_number_validator/en.yml
  config/locales/defra_ruby/validators/grid_reference_validator/en.yml
  config/locales/defra_ruby/validators/position_validator/en.yml
  lib/defra_ruby/validators/companies_house_number_validator.rb
  lib/defra_ruby/validators/concerns/can_validate_characters.rb
  lib/defra_ruby/validators/grid_reference_validator.rb
  spec/defra_ruby/validators/companies_house_number_validator_spec.rb
  spec/defra_ruby/validators/grid_reference_validator_spec.rb
  spec/support/shared_examples/validators/characters_validator.rb
Labels: housekeeping

#39 Update VCR cassettes
  spec/cassettes/company_no_inactive.yml
  spec/cassettes/company_no_not_found.yml
  spec/cassettes/company_no_valid.yml
Labels: housekeeping

#38 Add option to validate 'overseas' as business type
  README.md
  lib/defra_ruby/validators/business_type_validator.rb
  spec/defra_ruby/validators/business_type_validator_spec.rb
Labels: enhancement

#40 Add option to validate 'overseas' as location
  README.md
  lib/defra_ruby/validators/location_validator.rb
  spec/defra_ruby/validators/location_validator_spec.rb
Labels: enhancement

#41 Use attribute correct name during validation
  lib/defra_ruby/validators/business_type_validator.rb
  lib/defra_ruby/validators/email_validator.rb
  lib/defra_ruby/validators/grid_reference_validator.rb
  lib/defra_ruby/validators/location_validator.rb
  lib/defra_ruby/validators/phone_number_validator.rb
  lib/defra_ruby/validators/position_validator.rb
  lib/defra_ruby/validators/token_validator.rb
Labels: bug
