Repository DEFRA/defra-ruby-validators, pull requests merged in 2023-06, with the labels that each got.

#63 Add a check for all-zeroes companies house values
  .github/workflows/ci.yml
  .rubocop.yml
  .rubocop_todo.yml
  .ruby-version
  Gemfile
  defra_ruby_validators.gemspec
  lib/defra_ruby/validators/companies_house_number_validator.rb
  spec/defra_ruby/validators/business_type_validator_spec.rb
  spec/defra_ruby/validators/companies_house_number_validator_spec.rb
  spec/defra_ruby/validators/companies_house_service_spec.rb
  spec/defra_ruby/validators/configuration_spec.rb
  spec/defra_ruby/validators/email_validator_spec.rb
  spec/defra_ruby/validators/grid_reference_validator_spec.rb
  spec/defra_ruby/validators/location_validator_spec.rb
  spec/defra_ruby/validators/past_date_validator_spec.rb
  spec/defra_ruby/validators/phone_number_validator_spec.rb
  spec/defra_ruby/validators/position_validator_spec.rb
  spec/defra_ruby/validators/token_validator_spec.rb
  spec/defra_ruby/validators/true_false_validator_spec.rb
  spec/support/shared_examples/validators/characters_validator.rb
  spec/support/shared_examples/validators/invalid_record.rb
  spec/support/shared_examples/validators/length_validator.rb
  spec/support/shared_examples/validators/presence_validator.rb
  spec/support/shared_examples/validators/selection_validator.rb
Labels: bug

#64 Release/v2.5.1
  CHANGELOG.md
  defra_ruby_validators-2.5.1.gem
  lib/defra_ruby/validators/companies_house_number_validator.rb
  lib/defra_ruby/validators/version.rb
Labels: housekeeping

#65 Adding validator for mobile phone number
  README.md
  config/locales/defra_ruby/validators/mobile_phone_number_validator/en.yml
  lib/defra_ruby/validators.rb
  lib/defra_ruby/validators/mobile_phone_number_validator.rb
  spec/defra_ruby/validators/mobile_phone_number_validator_spec.rb
Labels: enhancement

#66 Release/v2.5.2
  CHANGELOG.md
  defra_ruby_validators-2.5.1.gem
  defra_ruby_validators-2.5.2.gem
  lib/defra_ruby/validators/version.rb
Labels: housekeeping
